# Análise dos Dados

**Perguntas de pesquisa:**
1. Existem diferenças nos padrões de preços e custos de sinistros por sexo?
2. Existe interação entre idade e sexo nas colisões? Homens jovens ou mulheres mais velhas se acidentam mais?

In [1]:
# carregando pacotes
import pandas as pd

# Esse foi o primeiro pacte carregado, mas no documento `relatorio.qmd` eue xplico todos os que eu uso.

In [2]:
# carregando a base bruta
dados_brutos = pd.read_csv("C:/Users/luiza/area_de_trabalho/Estatistica_UFLA/3º semestre/consultora-I/projeto-consultoria/bases/Autoseg2021A/arq_casco_comp.csv", 
                   delimiter= ";", decimal= ",")

dados_brutos.head()

C:\Users\luiza\AppData\Local\Temp\ipykernel_21840\3177268805.py:2: DtypeWarning: Columns (0: REGIAO) have mixed types. Specify dtype option on import or set low_memory=False.
  dados_brutos = pd.read_csv("C:/Users/luiza/area_de_trabalho/Estatistica_UFLA/3º semestre/consultora-I/projeto-consultoria/bases/Autoseg2021A/arq_casco_comp.csv",

,COD_TARIF,REGIAO,COD_MODELO,ANO_MODELO,SEXO,IDADE,EXPOSICAO1,PREMIO1,EXPOSICAO2,PREMIO2,...,INDENIZ1,FREQ_SIN2,INDENIZ2,FREQ_SIN3,INDENIZ3,FREQ_SIN4,INDENIZ4,FREQ_SIN9,INDENIZ9,ENVIO
0,9,11,515153-8,2014,J,0,16.821917,20984.153772,0,0,...,0,0,0,0,0,0,0,0,0,2021A
1,1,2,025081-3,2006,F,5,0.734247,421.130995,0,0,...,0,0,0,0,0,0,0,0,0,2021A
2,1,23,004318-4,2014,F,2,0.504110,309.683075,0,0,...,0,0,0,0,0,0,0,0,0,2021A
3,1,39,004354-0,2011,F,5,0.402740,257.049194,0,0,...,0,0,0,0,0,0,0,0,0,2021A
4,1,13,515021-3,1999,M,5,0.506849,947.028137,0,0,...,0,0,0,0,0,0,0,0,0,2021A

In [3]:
# vendo a classe
dados_brutos.info()

<class 'pandas.DataFrame'>
RangeIndex: 3390758 entries, 0 to 3390757
Data columns (total 22 columns):
 #   Column      Dtype
---  ------      -----
 0   COD_TARIF   int64
 1   REGIAO      object
 2   COD_MODELO  str
 3   ANO_MODELO  int64
 4   SEXO        str
 5   IDADE       int64
 6   EXPOSICAO1  float64
 7   PREMIO1     float64
 8   EXPOSICAO2  int64
 9   PREMIO2     int64
 10  IS_MEDIA    float64
 11  FREQ_SIN1   int64
 12  INDENIZ1    int64
 13  FREQ_SIN2   int64
 14  INDENIZ2    int64
 15  FREQ_SIN3   int64
 16  INDENIZ3    int64
 17  FREQ_SIN4   int64
 18  INDENIZ4    int64
 19  FREQ_SIN9   int64
 20  INDENIZ9    int64
 21  ENVIO       str
dtypes: float64(3), int64(15), object(1), str(3)
memory usage: 569.1+ MB

In [4]:
# Filtrando pra SP
base_sp = dados_brutos[dados_brutos["REGIAO"].isin(["10","11", "12","13"])]
base_sp.head()

,COD_TARIF,REGIAO,COD_MODELO,ANO_MODELO,SEXO,IDADE,EXPOSICAO1,PREMIO1,EXPOSICAO2,PREMIO2,...,INDENIZ1,FREQ_SIN2,INDENIZ2,FREQ_SIN3,INDENIZ3,FREQ_SIN4,INDENIZ4,FREQ_SIN9,INDENIZ9,ENVIO
32772,1,12,025257-3,2019,M,5,0.506849,726.885704,0,0,...,0,0,0,0,0,0,0,0,0,2021A
32788,3,12,017054-2,2018,F,2,0.504110,585.180298,0,0,...,0,0,0,0,0,0,0,0,0,2021A
32790,3,12,025257-3,2018,F,3,1.430137,1344.379581,0,0,...,0,0,0,0,0,0,0,0,0,2021A
32797,9,11,014050-3,2009,0,1,1.008219,667.618927,0,0,...,0,0,0,0,0,0,0,0,0,2021A
32799,3,13,066012-4,2017,J,5,0.506849,441.481674,0,0,...,0,0,0,0,0,0,0,0,0,2021A

In [5]:
# Vendo as classes de sp
base_sp.info()

<class 'pandas.DataFrame'>
Index: 438164 entries, 32772 to 3375101
Data columns (total 22 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   COD_TARIF   438164 non-null  int64
 1   REGIAO      438164 non-null  object
 2   COD_MODELO  438164 non-null  str
 3   ANO_MODELO  438164 non-null  int64
 4   SEXO        438164 non-null  str
 5   IDADE       438164 non-null  int64
 6   EXPOSICAO1  438164 non-null  float64
 7   PREMIO1     438164 non-null  float64
 8   EXPOSICAO2  438164 non-null  int64
 9   PREMIO2     438164 non-null  int64
 10  IS_MEDIA    438164 non-null  float64
 11  FREQ_SIN1   438164 non-null  int64
 12  INDENIZ1    438164 non-null  int64
 13  FREQ_SIN2   438164 non-null  int64
 14  INDENIZ2    438164 non-null  int64
 15  FREQ_SIN3   438164 non-null  int64
 16  INDENIZ3    438164 non-null  int64
 17  FREQ_SIN4   438164 non-null  int64
 18  INDENIZ4    438164 non-null  int64
 19  FREQ_SIN9   438164 non-null  int64
 20  INDENIZ9    438164 non-null  int64
 21  ENVIO       438164 non-null  str
dtypes: float64(3), int64(15), object(1), str(3)
memory usage: 76.9+ MB

In [6]:
# removendo o que eu não vou usar
base_sp_filtrada = base_sp.drop(["EXPOSICAO2", "PREMIO2", "IS_MEDIA"], axis=1)

base_sp_filtrada.head()

,COD_TARIF,REGIAO,COD_MODELO,ANO_MODELO,SEXO,IDADE,EXPOSICAO1,PREMIO1,FREQ_SIN1,INDENIZ1,FREQ_SIN2,INDENIZ2,FREQ_SIN3,INDENIZ3,FREQ_SIN4,INDENIZ4,FREQ_SIN9,INDENIZ9,ENVIO
32772,1,12,025257-3,2019,M,5,0.506849,726.885704,0,0,0,0,0,0,0,0,0,0,2021A
32788,3,12,017054-2,2018,F,2,0.504110,585.180298,0,0,0,0,0,0,0,0,0,0,2021A
32790,3,12,025257-3,2018,F,3,1.430137,1344.379581,0,0,0,0,0,0,0,0,0,0,2021A
32797,9,11,014050-3,2009,0,1,1.008219,667.618927,0,0,0,0,0,0,0,0,0,0,2021A
32799,3,13,066012-4,2017,J,5,0.506849,441.481674,0,0,0,0,0,0,0,0,0,0,2021A

In [7]:
# Vendo as classes de sp depois de filtrar
base_sp_filtrada.info()

# verificando a base 
# dados numéricos

base_sp_filtrada.describe()

<class 'pandas.DataFrame'>
Index: 438164 entries, 32772 to 3375101
Data columns (total 19 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   COD_TARIF   438164 non-null  int64
 1   REGIAO      438164 non-null  object
 2   COD_MODELO  438164 non-null  str
 3   ANO_MODELO  438164 non-null  int64
 4   SEXO        438164 non-null  str
 5   IDADE       438164 non-null  int64
 6   EXPOSICAO1  438164 non-null  float64
 7   PREMIO1     438164 non-null  float64
 8   FREQ_SIN1   438164 non-null  int64
 9   INDENIZ1    438164 non-null  int64
 10  FREQ_SIN2   438164 non-null  int64
 11  INDENIZ2    438164 non-null  int64
 12  FREQ_SIN3   438164 non-null  int64
 13  INDENIZ3    438164 non-null  int64
 14  FREQ_SIN4   438164 non-null  int64
 15  INDENIZ4    438164 non-null  int64
 16  FREQ_SIN9   438164 non-null  int64
 17  INDENIZ9    438164 non-null  int64
 18  ENVIO       438164 non-null  str
dtypes: float64(2), int64(13), object(1), str(3)
memory usage: 66.9+ MB

,COD_TARIF,ANO_MODELO,IDADE,EXPOSICAO1,PREMIO1,FREQ_SIN1,INDENIZ1,FREQ_SIN2,INDENIZ2,FREQ_SIN3,INDENIZ3,FREQ_SIN4,INDENIZ4,FREQ_SIN9,INDENIZ9
count,438164.000000,438164.000000,438164.000000,438164.000000,4.381640e+05,438164.000000,4.381640e+05,438164.000000,438164.000000,438164.000000,4.381640e+05,438164.000000,438164.000000,438164.00000,438164.000000
mean,2.262934,2012.346421,2.665988,3.236292,4.394520e+03,0.123132,1.096679e+03,0.199398,1421.117515,0.020885,8.316395e+02,0.001082,40.615678,1.86907,883.523895
std,1.942625,13.762429,1.780039,12.396361,1.616469e+04,0.712017,1.107459e+04,1.041599,8253.380923,0.164729,8.716850e+03,0.034166,2171.072351,9.01703,6842.718340
min,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000
25%,1.000000,2009.000000,1.000000,0.326027,3.459659e+02,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000
50%,1.000000,2014.000000,3.000000,0.520548,9.868456e+02,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000
75%,3.000000,2017.000000,4.000000,1.895890,2.952047e+03,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.00000,97.000000
max,9.000000,2022.000000,5.000000,1567.761633,2.166847e+06,60.000000,1.192687e+06,97.000000,715444.000000,10.000000,1.000501e+06,2.000000,422114.000000,753.00000,837984.000000

In [8]:
# vendo o tamanho final da base
print(base_sp_filtrada.shape)
dir(base_sp_filtrada)

(438164, 19)

['ANO_MODELO',
 'COD_MODELO',
 'COD_TARIF',
 'ENVIO',
 'EXPOSICAO1',
 'FREQ_SIN1',
 'FREQ_SIN2',
 'FREQ_SIN3',
 'FREQ_SIN4',
 'FREQ_SIN9',
 'IDADE',
 'INDENIZ1',
 'INDENIZ2',
 'INDENIZ3',
 'INDENIZ4',
 'INDENIZ9',
 'PREMIO1',
 'REGIAO',
 'SEXO',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [9]:
# Vendo se tem NAs em cada coluna
print(base_sp_filtrada.isna().sum())

COD_TARIF     0
REGIAO        0
COD_MODELO    0
ANO_MODELO    0
SEXO          0
IDADE         0
EXPOSICAO1    0
PREMIO1       0
FREQ_SIN1     0
INDENIZ1      0
FREQ_SIN2     0
INDENIZ2      0
FREQ_SIN3     0
INDENIZ3      0
FREQ_SIN4     0
INDENIZ4      0
FREQ_SIN9     0
INDENIZ9      0
ENVIO         0
dtype: int64

In [10]:
print(base_sp_filtrada["SEXO"].value_counts())

SEXO
M    189430
F    132493
J     76720
0     39521
Name: count, dtype: int64

Temos nessa base filtrada para o estado de SP somente 189.430 pessoas do sexo masculino e 132.493 do feminino. Esse dado é importante, pois como a minha análise terá como centro a diferenciação entre os sexos.

In [11]:
## 1. Padrões de preços e custos por sexo
# Possíveis diferenças nos padrões de preços e nos 
# custos dos sinistros em relação ao sexo dos proprietários

In [12]:
# frequência e indenização
colunas_frequencia = ["FREQ_SIN1", "FREQ_SIN2", "FREQ_SIN3", "FREQ_SIN4", "FREQ_SIN9"]
colunas_indenizacao = ["INDENIZ1", "INDENIZ2", "INDENIZ3", "INDENIZ4", "INDENIZ9"]

# agrupando 
agrupado = base_sp_filtrada.groupby("SEXO").agg({
    "EXPOSICAO1": "sum",
    "PREMIO1": "sum",
    **{col: "sum" for col in colunas_frequencia},  
    **{col: "sum" for col in colunas_indenizacao}  
}).reset_index()

# medianas diretas da base original
medianas = base_sp_filtrada.groupby("SEXO").agg(
    Mediana_Premio   = ("PREMIO1",  "median"),
    Mediana_Indeniz2 = ("INDENIZ2", "median"),
    Mediana_Indeniz3 = ("INDENIZ3", "median")
).reset_index()

# totais consolidados 
agrupado["TOTAL_FREQ"] = agrupado[colunas_frequencia].sum(axis=1)
agrupado["TOTAL_INDENIZ"] = agrupado[colunas_indenizacao].sum(axis=1)

# analises
analise_sexo = pd.DataFrame()
analise_sexo["Sexo"] = agrupado["SEXO"]

# Prêmio Médio
analise_sexo["Premio_Medio"] = agrupado["PREMIO1"] / agrupado["EXPOSICAO1"]

# Frequência Sinistral Total
analise_sexo["Freq_Sinistral_Total"] = agrupado["TOTAL_FREQ"] / agrupado["EXPOSICAO1"]

# Custo Médio por Exposto (Sinistro Médio)
analise_sexo["Custo_Medio_Exposto"] = agrupado["TOTAL_INDENIZ"] / agrupado["EXPOSICAO1"]

# Severidades Específicas
analise_sexo["Severidade_Roubo"] = agrupado["INDENIZ1"] / agrupado["FREQ_SIN1"]
analise_sexo["Severidade_Colisao_Parcial"] = agrupado["INDENIZ2"] / agrupado["FREQ_SIN2"]
analise_sexo["Severidade_Perda_Total"] = agrupado["INDENIZ3"] / agrupado["FREQ_SIN3"]

# Preenchendo possíveis valores nulos
analise_sexo = analise_sexo.fillna(0)

print(analise_sexo.to_string(index=False))

Sexo  Premio_Medio  Freq_Sinistral_Total  Custo_Medio_Exposto  Severidade_Roubo  Severidade_Colisao_Parcial  Severidade_Perda_Total
   0   1217.328996              2.895852         14408.841529      21181.110971                 7268.388240            42990.089253
   F   1214.220418              0.817145          1023.006038       6260.286074                 6757.319634            36699.810437
   J   1733.140612              0.000000             0.000000          0.000000                    0.000000                0.000000
   M   1362.036287              0.669806          1243.806520       8473.633558                 7292.191351            39458.094550

In [13]:
# totais consolidados 
agrupado["TOTAL_FREQ"] = agrupado[colunas_frequencia].sum(axis=1)
agrupado["TOTAL_INDENIZ"] = agrupado[colunas_indenizacao].sum(axis=1)

# df das análises principais
analise_sexo = pd.DataFrame()
# AJUSTE AQUI: Mantendo "SEXO" em maiúsculo para alinhar com o banco de dados
analise_sexo["SEXO"] = agrupado["SEXO"] 
analise_sexo["Premio_Medio"] = agrupado["PREMIO1"] / agrupado["EXPOSICAO1"]
analise_sexo["Freq_Sinistral_Total"] = agrupado["TOTAL_FREQ"] / agrupado["EXPOSICAO1"]
analise_sexo["Custo_Medio_Exposto"] = agrupado["TOTAL_INDENIZ"] / agrupado["EXPOSICAO1"]
analise_sexo["Severidade_Roubo"] = agrupado["INDENIZ1"] / agrupado["FREQ_SIN1"]
analise_sexo["Severidade_Colisao_Parcial"] = agrupado["INDENIZ2"] / agrupado["FREQ_SIN2"]
analise_sexo["Severidade_Perda_Total"] = agrupado["INDENIZ3"] / agrupado["FREQ_SIN3"]

analise_sexo = analise_sexo.merge(medianas, on="SEXO", how="left")

analise_sexo = analise_sexo.fillna(0)

print(analise_sexo.to_string(index=False))

SEXO  Premio_Medio  Freq_Sinistral_Total  Custo_Medio_Exposto  Severidade_Roubo  Severidade_Colisao_Parcial  Severidade_Perda_Total  Mediana_Premio  Mediana_Indeniz2  Mediana_Indeniz3
   0   1217.328996              2.895852         14408.841529      21181.110971                 7268.388240            42990.089253      201.311478               0.0               0.0
   F   1214.220418              0.817145          1023.006038       6260.286074                 6757.319634            36699.810437     1061.845612               0.0               0.0
   J   1733.140612              0.000000             0.000000          0.000000                    0.000000                0.000000     1021.859119               0.0               0.0
   M   1362.036287              0.669806          1243.806520       8473.633558                 7292.191351            39458.094550     1153.306938               0.0               0.0

In [14]:
# confirmando os nomes das colunas
print(base_sp_filtrada.columns.tolist())

['COD_TARIF', 'REGIAO', 'COD_MODELO', 'ANO_MODELO', 'SEXO', 'IDADE', 'EXPOSICAO1', 'PREMIO1', 'FREQ_SIN1', 'INDENIZ1', 'FREQ_SIN2', 'INDENIZ2', 'FREQ_SIN3', 'INDENIZ3', 'FREQ_SIN4', 'INDENIZ4', 'FREQ_SIN9', 'INDENIZ9', 'ENVIO']

# 2. Colisões por Idade × Sexo

In [15]:
# Tabela 1

import pandas as pd

# filtrando a base só com feminino ("F") e masculino ("M")
base_colisao = base_sp_filtrada[base_sp_filtrada["SEXO"].isin(["F", "M"])].copy()

# agrupando por IDADE e SEXO 
agrupado_idade_sexo = base_colisao.groupby(["IDADE", "SEXO"]).agg({
    "EXPOSICAO1": "sum",
    "FREQ_SIN2": "sum",
    "INDENIZ2": "sum",
    "FREQ_SIN3": "sum",
    "INDENIZ3": "sum"
}).reset_index()

# medianas diretas da base original
medianas_idade_sexo = base_colisao.groupby(["IDADE", "SEXO"]).agg(
    Mediana_Indeniz2 = ("INDENIZ2", "median"),
    Mediana_Indeniz3 = ("INDENIZ3", "median")
).reset_index()

# tabela final com os calculos
analise_idade_sexo = pd.DataFrame()
analise_idade_sexo["Idade"] = agrupado_idade_sexo["IDADE"]
analise_idade_sexo["Sexo"] = agrupado_idade_sexo["SEXO"]

# colisão parcial
analise_idade_sexo["Freq_Colisao_Parcial"] = agrupado_idade_sexo["FREQ_SIN2"] / agrupado_idade_sexo["EXPOSICAO1"]
analise_idade_sexo["Severidade_Colisao_Parcial"] = agrupado_idade_sexo["INDENIZ2"] / agrupado_idade_sexo["FREQ_SIN2"]

# perda total
analise_idade_sexo["Freq_Perda_Total"] = agrupado_idade_sexo["FREQ_SIN3"] / agrupado_idade_sexo["EXPOSICAO1"]
analise_idade_sexo["Severidade_Perda_Total"] = agrupado_idade_sexo["INDENIZ3"] / agrupado_idade_sexo["FREQ_SIN3"]

# limpar divisões por zero
analise_idade_sexo = analise_idade_sexo.fillna(0)

# ordenar por Idade para facilitar a leitura
analise_idade_sexo = analise_idade_sexo.sort_values(by=["Idade", "Sexo"])

print(analise_idade_sexo.head(30).to_string(index=False))

 Idade Sexo  Freq_Colisao_Parcial  Severidade_Colisao_Parcial  Freq_Perda_Total  Severidade_Perda_Total
     0    F              0.114596                10473.368015          0.023405            45368.169811
     0    M              0.165737                 9156.404772          0.032141            49220.076063
     1    F              0.076478                 6523.002775          0.007641            31049.740741
     1    M              0.070773                 7472.214896          0.013221            28953.470588
     2    F              0.054879                 6380.123802          0.004310            34080.693780
     2    M              0.051540                 7119.081568          0.007016            34224.990921
     3    F              0.048098                 6868.889951          0.004026            36505.486134
     3    M              0.053629                 7409.903883          0.006619            41272.899365
     4    F              0.047189                 6656.138104          0.003982            37444.854626
     4    M              0.047520                 7066.373022          0.005412            38822.059740
     5    F              0.045840                 6426.300744          0.003548            35894.723112
     5    M              0.044791                 6967.386973          0.003817            41127.048603

Legenda das idades: 
0 - Não informada; 1 - Entre 18 e 25 anos; 2 - Entre 26 e 35 anos; 3 - Entre 36 e 45 anos; 4 - Entre 46 e 55 anos; 5 - Maior que 55 anos

# TESTE T

In [16]:
from scipy import stats
import numpy as np

# Lembrando que aqui se não tem essas bibliotecas é necessário instalar.

# excluindo J de jurídico

masculino = base_sp_filtrada[base_sp_filtrada["SEXO"] == "M"]
feminino  = base_sp_filtrada[base_sp_filtrada["SEXO"] == "F"]

def teste_t(var, nome):
    grupo_m = masculino[var].dropna()
    grupo_f = feminino[var].dropna()
    
    t_stat, p_valor = stats.ttest_ind(grupo_m, grupo_f, equal_var=False)
    
    media_m, media_f = grupo_m.mean(), grupo_f.mean()
    dp_pool = np.sqrt((grupo_m.std()**2 + grupo_f.std()**2) / 2)
    cohens_d = (media_m - media_f) / dp_pool
    
    print(nome)
    print("Média Masculino:", media_m)
    print("Média Feminino:", media_f)
    print("Estatística t:", t_stat)
    print("p-valor:", p_valor)
    
    # Interpretação automática do efeito
    d = abs(cohens_d)
    if d < 0.2:
        efeito = "negligenciável"
    elif d < 0.5:
        efeito = "pequeno"
    elif d < 0.8:
        efeito = "médio"
    else:
        efeito = "grande"
    
    if p_valor < 0.05:
        sig = "SIM"
    else:
        sig = "NÃO"
    
    print("Significativo (alfa=0.05):", sig, "| Tamanho do efeito:", efeito)
    print()

# Rodando para as variáveis de interesse
teste_t("PREMIO1",  "Prêmio médio (PREMIO1)")
teste_t("FREQ_SIN2", "Frequência de colisão (FREQ_SIN2)")
teste_t("INDENIZ2",  "Custo de indenização por colisão (INDENIZ2)")

Prêmio médio (PREMIO1)
Média Masculino: 4828.005850142176
Média Feminino: 4670.530754373596
Estatística t: 2.931934784161032
p-valor: 0.003368842511914902
Significativo (alfa=0.05): SIM | Tamanho do efeito: negligenciável

Frequência de colisão (FREQ_SIN2)
Média Masculino: 0.18456421897270758
Média Feminino: 0.19466688806201082
Estatística t: -3.282105442583179
p-valor: 0.001030481650579459
Significativo (alfa=0.05): SIM | Tamanho do efeito: negligenciável

Custo de indenização por colisão (INDENIZ2)
Média Masculino: 1345.8776012247267
Média Feminino: 1315.4263847901398
Estatística t: 1.1925554234153943
p-valor: 0.23304452486076102
Significativo (alfa=0.05): NÃO | Tamanho do efeito: negligenciável

# Gráficos e Tabelas

In [17]:
# Tabela 1
print(analise_sexo.to_string(index=False))

SEXO  Premio_Medio  Freq_Sinistral_Total  Custo_Medio_Exposto  Severidade_Roubo  Severidade_Colisao_Parcial  Severidade_Perda_Total  Mediana_Premio  Mediana_Indeniz2  Mediana_Indeniz3
   0   1217.328996              2.895852         14408.841529      21181.110971                 7268.388240            42990.089253      201.311478               0.0               0.0
   F   1214.220418              0.817145          1023.006038       6260.286074                 6757.319634            36699.810437     1061.845612               0.0               0.0
   J   1733.140612              0.000000             0.000000          0.000000                    0.000000                0.000000     1021.859119               0.0               0.0
   M   1362.036287              0.669806          1243.806520       8473.633558                 7292.191351            39458.094550     1153.306938               0.0               0.0

In [18]:
# Gráfico 1   !!!!!!!!!!!!!!!

import matplotlib.pyplot as plt

# removendo sexo 0 e J
graf3 = analise_sexo[analise_sexo["Sexo"].isin(["F", "M"])]

sexos  = graf3["Sexo"].tolist()
precos = graf3["Premio_Medio"].tolist()
cores  = ["salmon", "steelblue"]

plt.figure(figsize=(6, 5))
barras = plt.bar(sexos, precos, color=cores, width=0.4)

for barra, valor in zip(barras, precos):
    plt.text(barra.get_x() + barra.get_width() / 2, barra.get_height() + 20,
             "R$ " + str(round(valor, 2)), ha="center", va="bottom", fontsize=10)

plt.title("Prêmio Médio por Sexo")
plt.xlabel("Sexo")
plt.ylabel("Prêmio Médio (R$)")
plt.ylim(0, max(precos) * 1.2)  # 20% de espaço acima da maior barra
plt.tight_layout()
plt.show()

KeyError: 'Sexo'

In [ ]:
#| warning: false
#| message: false
#| title: "Tabela 2: Métricas por Idade e Sexo"
#| column: screen

import pandas as pd

# filtrando a base só com Feminino ("F") e Masculino ("M")
base_colisao = base_sp_filtrada[base_sp_filtrada["SEXO"].isin(["F", "M"])].copy()

# agrupando por IDADE e SEXO 
agrupado_idade_sexo = base_colisao.groupby(["IDADE", "SEXO"]).agg({
    "EXPOSICAO1": "sum",
    "FREQ_SIN2": "sum",
    "INDENIZ2": "sum",
    "FREQ_SIN3": "sum",
    "INDENIZ3": "sum"
}).reset_index()

# medianas diretas da base original
medianas_idade_sexo = base_colisao.groupby(["IDADE", "SEXO"]).agg(
    Mediana_Indeniz2 = ("INDENIZ2", "median"),
    Mediana_Indeniz3 = ("INDENIZ3", "median")
).reset_index()

# tabela final com as métricas calculadas
analise_idade_sexo = pd.DataFrame()
analise_idade_sexo["Idade"] = agrupado_idade_sexo["IDADE"]
analise_idade_sexo["Sexo"] = agrupado_idade_sexo["SEXO"]

# colisão parcial
analise_idade_sexo["Freq_Colisao_Parcial"] = agrupado_idade_sexo["FREQ_SIN2"] / agrupado_idade_sexo["EXPOSICAO1"]
analise_idade_sexo["Severidade_Colisao_Parcial"] = agrupado_idade_sexo["INDENIZ2"] / agrupado_idade_sexo["FREQ_SIN2"]

# perda total
analise_idade_sexo["Freq_Perda_Total"] = agrupado_idade_sexo["FREQ_SIN3"] / agrupado_idade_sexo["EXPOSICAO1"]
analise_idade_sexo["Severidade_Perda_Total"] = agrupado_idade_sexo["INDENIZ3"] / agrupado_idade_sexo["FREQ_SIN3"]

# adicionando medianas
analise_idade_sexo["Mediana_Indeniz2"] = medianas_idade_sexo["Mediana_Indeniz2"].values
analise_idade_sexo["Mediana_Indeniz3"] = medianas_idade_sexo["Mediana_Indeniz3"].values

# limpando divisões por zero
analise_idade_sexo = analise_idade_sexo.fillna(0)

# ordenandp por Idade para facilitar a leitura
analise_idade_sexo = analise_idade_sexo.sort_values(by=["Idade", "Sexo"])

# ajustando para mostrar as %

formatacao_tabela2 = {
    "Freq_Colisao_Parcial": "{:.2%}",
    "Severidade_Colisao_Parcial": "R$ {:,.2f}",
    "Freq_Perda_Total": "{:.2%}",
    "Severidade_Perda_Total": "R$ {:,.2f}",
    "Mediana_Indeniz2": "R$ {:,.2f}",
    "Mediana_Indeniz3": "R$ {:,.2f}"
}

colunas_destaque = [
    "Freq_Colisao_Parcial", 
    "Severidade_Colisao_Parcial", 
    "Freq_Perda_Total", 
    "Severidade_Perda_Total"
]


tabela2_dashboard = analise_idade_sexo.head(30).style \
    .format(formatacao_tabela2, decimal=',', thousands='.') \
    .background_gradient(subset=colunas_destaque, cmap='Blues', axis=0) \
    .set_properties(**{'text-align': 'right', 'padding': '10px'}) \
    .set_properties(subset=['Idade', 'Sexo'], **{'text-align': 'left', 'font-weight': 'bold'}) \
    .set_table_styles([
        {
            'selector': 'th',
            'props': [
                ('background-color', '#1E3A8A'),
                ('color', 'white'),
                ('font-weight', 'bold'),
                ('text-align', 'center'),
                ('padding', '12px')
            ]
        },
        {
            'selector': 'tr:nth-child(even)',
            'props': [('background-color', '#F8FAFC')]
        }
    ]) \
    .hide(axis='index')

tabela2_dashboard

In [ ]:
# Gráfico 2: Frequência de colisão por Idade × Sexo (linhas)
import matplotlib.pyplot as plt

# removendo idade 0
graf1 = analise_idade_sexo[analise_idade_sexo["Idade"] != 0]

masculino_g1 = graf1[graf1["Sexo"] == "M"]
feminino_g1  = graf1[graf1["Sexo"] == "F"]

plt.figure(figsize=(12, 5))
plt.plot(masculino_g1["Idade"], masculino_g1["Freq_Colisao_Parcial"], label="Masculino", color="steelblue", marker="o", markersize=3)
plt.plot(feminino_g1["Idade"],  feminino_g1["Freq_Colisao_Parcial"],  label="Feminino",  color="salmon",   marker="o", markersize=3)

plt.title("Frequência de Colisão Parcial por Idade e Sexo")
plt.xlabel("Idade")
plt.ylabel("Frequência de Colisão Parcial")
plt.legend()
plt.tight_layout()
plt.show()

In [ ]:
# Gráfico 3: Perda Total × Idade × Sexo (linhas)

import matplotlib.pyplot as plt

# removendo idade 0
graf2 = analise_idade_sexo[analise_idade_sexo["Idade"] != 0]

masculino_g2 = graf2[graf2["Sexo"] == "M"]
feminino_g2  = graf2[graf2["Sexo"] == "F"]

plt.figure(figsize=(12, 5))
plt.plot(masculino_g2["Idade"], masculino_g2["Freq_Perda_Total"], label="Masculino", color="steelblue", marker="o", markersize=3)
plt.plot(feminino_g2["Idade"],  feminino_g2["Freq_Perda_Total"],  label="Feminino",  color="salmon",   marker="o", markersize=3)

plt.title("Frequência de Perda Total por Idade e Sexo")
plt.xlabel("Idade")
plt.ylabel("Frequência de Perda Total")
plt.legend()
plt.tight_layout()
plt.show()